### PR TITLE
Add/docs logo

### PR DESCRIPTION
**Pull request by vsoch**
This will add pretty documentation and a logo. I might need a few shots to get it working on GitHub pages since there seems to be a CNAME (I hope it serves https...)

### CODE REVIEW

**Comment by yarikoptic** [comment]
What are the copyright/license on added exterior assets? Should be noted somewhere

**Comment by vsoch** [comment]
The docsy jekyll is a template I made (and it already includes a license plus reference to the original). The logo I modified from something on wikimedia commons.

**Comment by vsoch** [comment]
I'm going to merge it because I need to test the deploy, but please PR with however you'd like assets documented.

**Comment by vsoch** [comment]
@yarikoptic please see #16 this is an issue that needs your immediate attention, I cannot move forward until this is resolved.

**Pull request merged**
