### PR TITLE
first shot at --from

### PR DESCRIPTION
**Pull request by vsoch**
I didn't sleep last night and I've been working on this all morning, trying to meet all the use cases that have been wanted in various issues. I'm frustrated with the current state of the library because I feel that it is getting messy - before it was just a simple "you update from GitHub contributors and that's the source of truth" but it's been requested that "I want to update from this file to this other one! I want to include a mailmap!" and I'm just frustrated because it feels like the library is getting worse. Anyway, here is a nice PR to make it much worse with `--from` - or maybe I just need to step back from this. @yarikoptic I'm really struggling to understand what you want, saying "I just want it to magically do the things I want" is not specific enough for me to develop this. :/ 

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
I liked the design before because it was simple and clean, and now it's just messy, disorganized, and I'm not even sure consistent.

**Comment by yarikoptic** [comment]
Sorry if we got carried away a bit. Well, fwiw, in my complaints I just keep reiterating my target use case which started this project - from all-contributors to zenodo. Additional integrations (GitHub, mailmap) were suggested as an additional source of information to assist with establishing necessary linkage information. May be indeed it is worth stepping back just for a little, try on different projects. My target use cases are OBC (tricky that some have no GitHub) and posters platform (tricky since not all committers are contributors), but later I will also try in datalad which iirc had none yet (tricky since big and aged). Datalad handbook also uses all contributors and is a nice simple use case.

Meanwhile Happy 4th of July (also a birthday of the youngest kid of mine).

**Comment by vsoch** [comment]
Closes #32 and #37.

**Comment by vsoch** [comment]
I think that use case should be covered now, I added an examples page for it. I'm going to merge because I want to work on something else, but if you want to test again for your use cases please go ahead. Yeah over 4 hours / day on this project I'm a bit burned out from it, especially because it's getting worse. :/

**Pull request merged**
